### ISSUE TITLE
How to run examples?

### ISSUE THREAD

**Issue by kgerheiser** [Juee14Desai/HOTI_Tutorial_Examples#1]
First, when I try to build the example the compiler can't find `shared.h`

https://github.com/Juee14Desai/HOTI_Tutorial_Examples/blob/f0bfb081eaa5f780f23a7f539424dc6e06b83741/2023/example_msg.c#L39

```
example_msg.c:39:10: fatal error: shared.h: No such file or directory
```

I remove that and it builds, but when I run I get a segfault.  I am using libfabric 1.18.1 on Ubuntu 22.

```
gcc example_msg.c -o example -L${FABRIC_PREFIX}/lib -I${FABRIC_PREFIX}/include -lfabric
./example
Server started with addr 0.0.0.0
Segmentation fault
```

If I turn on `FI_LOG_LEVEL=debug`

```
libfabric:1149:1693081178::core:core:fi_getinfo_():1213<debug> hints prov_name: tcp
libfabric:1149:1693081178::ofi_rxm:core:ofi_check_ep_type():667<info> unsupported endpoint type
libfabric:1149:1693081178::ofi_rxm:core:ofi_check_ep_type():668<info> Supported: FI_EP_RDM
libfabric:1149:1693081178::ofi_rxm:core:ofi_check_ep_type():668<info> Requested: FI_EP_MSG
libfabric:1149:1693081178::ofi_rxm:core:ofi_check_ep_type():667<info> unsupported endpoint type
libfabric:1149:1693081178::ofi_rxm:core:ofi_check_ep_type():668<info> Supported: FI_EP_RDM
libfabric:1149:1693081178::ofi_rxm:core:ofi_check_ep_type():668<info> Requested: FI_EP_MSG
libfabric:1149:1693081178::ofi_rxm:core:ofi_check_ep_type():667<info> unsupported endpoint type
libfabric:1149:1693081178::ofi_rxm:core:ofi_check_ep_type():668<info> Supported: FI_EP_RDM
libfabric:1149:1693081178::ofi_rxm:core:ofi_check_ep_type():668<info> Requested: FI_EP_MSG
libfabric:1149:1693081178::ofi_rxm:core:ofi_check_ep_type():667<info> unsupported endpoint type
libfabric:1149:1693081178::ofi_rxm:core:ofi_check_ep_type():668<info> Supported: FI_EP_RDM
libfabric:1149:1693081178::ofi_rxm:core:ofi_check_ep_type():668<info> Requested: FI_EP_MSG
libfabric:1149:1693081178::ofi_rxm:core:ofi_check_ep_type():667<info> unsupported endpoint type
libfabric:1149:1693081178::ofi_rxm:core:ofi_check_ep_type():668<info> Supported: FI_EP_RDM
libfabric:1149:1693081178::ofi_rxm:core:ofi_check_ep_type():668<info> Requested: FI_EP_MSG
libfabric:1149:1693081178::core:core:fi_getinfo_():1251<info> fi_getinfo: provider ofi_rxm returned -61 (No data available)
libfabric:1149:1693081178::ofi_rxd:core:ofi_check_ep_type():667<info> unsupported endpoint type
libfabric:1149:1693081178::ofi_rxd:core:ofi_check_ep_type():668<info> Supported: FI_EP_RDM
libfabric:1149:1693081178::ofi_rxd:core:ofi_check_ep_type():668<info> Requested: FI_EP_MSG
libfabric:1149:1693081178::core:core:fi_getinfo_():1251<info> fi_getinfo: provider ofi_rxd returned -61 (No data available)
libfabric:1149:1693081178::tcp:core:util_getinfo():157<debug> checking info
libfabric:1149:1693081178::tcp:core:ofi_check_ep_attr():745<info> Provider requires use of shared rx context
libfabric:1149:1693081178::tcp:core:ofi_check_ep_type():667<info> unsupported endpoint type
libfabric:1149:1693081178::tcp:core:ofi_check_ep_type():668<info> Supported: FI_EP_RDM
libfabric:1149:1693081178::tcp:core:ofi_check_ep_type():668<info> Requested: FI_EP_MSG
libfabric:1149:1693081178::tcp:core:fi_param_get_():372<info> variable iface=<not set>
libfabric:1149:1693081178::tcp:core:ofi_get_list_of_addr():2146<info> Available addr: 172.26.199.173, iface name: eth0, speed: 10000
libfabric:1149:1693081178::tcp:core:ofi_insert_loopback_addr():1977<info> available addr: : fi_sockaddr_in://127.0.0.1:0
libfabric:1149:1693081178::tcp:core:ofi_insert_loopback_addr():1992<info> available addr: : fi_sockaddr_in6://[::1]:0
libfabric:1149:1693081178::core:core:fi_getinfo_():1264<debug> fi_getinfo: provider tcp returned success
libfabric:1149:1693081178::ofi_mrail:fabric:mrail_get_core_info():288<warn> OFI_MRAIL_ADDR_STRC env variable not set!
libfabric:1149:1693081178::core:core:fi_getinfo_():1251<info> fi_getinfo: provider ofi_mrail returned -61 (No data available)
libfabric:1149:1693081178::core:core:fi_fabric_():1452<info> Opened fabric: tcp
libfabric:1149:1693081178::tcp:core:ofi_check_rx_attr():805<info> Tx only caps ignored in Rx caps
libfabric:1149:1693081178::tcp:core:ofi_check_tx_attr():903<info> Rx only caps ignored in Tx caps
libfabric:1149:1693081178::tcp:core:ofi_check_rx_attr():805<info> Tx only caps ignored in Rx caps
libfabric:1149:1693081178::tcp:core:ofi_check_rx_attr():835<info> comp_order not supported
libfabric:1149:1693081178::tcp:core:ofi_check_rx_attr():836<info> Supported:
libfabric:1149:1693081178::tcp:core:ofi_check_rx_attr():836<info> Requested: FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_RAS, FI_ORDER_WAR, FI_ORDER_WAW, FI_ORDER_WAS, FI_ORDER_SAR, FI_ORDER_SAW, FI_ORDER_SAS
libfabric:1149:1693081178::tcp:core:ofi_check_ep_type():667<info> unsupported endpoint type
libfabric:1149:1693081178::tcp:core:ofi_check_ep_type():668<info> Supported: FI_EP_RDM
libfabric:1149:1693081178::tcp:core:ofi_check_ep_type():668<info> Requested: FI_EP_MSG
libfabric:1149:1693081178::tcp:core:ofi_check_rx_attr():805<info> Tx only caps ignored in Rx caps
libfabric:1149:1693081178::tcp:core:ofi_check_tx_attr():903<info> Rx only caps ignored in Tx caps
libfabric:1149:1693081178::tcp:core:ofi_check_rx_attr():805<info> Tx only caps ignored in Rx caps
libfabric:1149:1693081178::tcp:core:ofi_check_rx_attr():835<info> comp_order not supported
libfabric:1149:1693081178::tcp:core:ofi_check_rx_attr():836<info> Supported:
libfabric:1149:1693081178::tcp:core:ofi_check_rx_attr():836<info> Requested: FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_RAS, FI_ORDER_WAR, FI_ORDER_WAW, FI_ORDER_WAS, FI_ORDER_SAR, FI_ORDER_SAW, FI_ORDER_SAS
libfabric:1149:1693081178::tcp:core:ofi_check_ep_type():667<info> unsupported endpoint type
libfabric:1149:1693081178::tcp:core:ofi_check_ep_type():668<info> Supported: FI_EP_RDM
libfabric:1149:1693081178::tcp:core:ofi_check_ep_type():668<info> Requested: FI_EP_MSG
Server started with addr 0.0.0.0
libfabric:1149:1693081178::tcp:eq:ofi_eq_sread():180<warn> EQ not configured for sread
Segmentation fault
```

**Comment by kgerheiser** [comment]
I added `eq_attr.wait_obj = FI_WAIT_UNSPEC` before calling `fi_eq_open` and that seems to have worked.

https://github.com/Juee14Desai/HOTI_Tutorial_Examples/blob/f0bfb081eaa5f780f23a7f539424dc6e06b83741/2023/example_msg.c#L139

**Comment by Juee14Desai** [comment]
Hi Kyle,

I have updated example_msg with a cleaner code and also resolved the issue that you were seeing.
You are correct. If we initialize fi_eq_attr with FI_WAIT_UNSPEC we will not see segmentation fault. I have fixed this in recent commit.

**Comment by kgerheiser** [comment]
What about `#include <shared.h>`? That header include should be removed.

**Comment by ritularya** [comment]
I am trying to learn libfabric and I am completely new to this. I am able to compile the code even with shared.h but in complete_connection the info my fi_domain is showing null.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7db6311 in xnet_domain_open (fabric_fid=0x555555563430, info=0x0,
    domain_fid=0x5555555590a8 <domain>, context=0x0) at prov/tcp/src/xnet_domain.c:439
439             if (info->ep_attr->type == FI_EP_RDM &&
(gdb) bt
#0  0x00007ffff7db6311 in xnet_domain_open (fabric_fid=0x555555563430, info=0x0,
    domain_fid=0x5555555590a8 <domain>, context=0x0) at prov/tcp/src/xnet_domain.c:439
#1  0x000055555555535a in fi_domain (fabric=0x555555563430, info=0x0, domain=0x5555555590a8 <domain>,
    context=0x0) at /usr/include/rdma/fi_domain.h:328
#2  0x0000555555555d4f in complete_connection () at lfabric_msg.c:231
#3  0x00005555555565a9 in main (argc=1, argv=0x7fffffffe278) at lfabric_msg.c:510
